name: deploy

on:
  push:
    branches:
      - release/live

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          cp -r ${{ github.workspace }}/. /home/runner/vps-manager/
          cd /home/runner/vps-manager
          docker compose up -d --build
