name: deploy

on:
  push:
    branches:
      - release/live

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        working-directory: /home/runner/vps-manager
        run: |
          git pull
          docker compose up -d --build
